### ISSUE TITLE
Unsubscribing Alerts does not work

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/alerts#31] opened 2017-08-08 00:25 UTC
Stop receiving alerts link on email does not work.

> To stop receiving alerts for New records for LOWER MURRAY, click here. To stop receiving all Atlas of Living Australia alerts, click here.

**Comment by nickdos** [comment] 2017-09-14 00:33
Same bug as #30

**Comment by matthewandrews** [comment] 2018-08-13 01:26
Closed as duplicate of #30

**Closed by matthewandrews** 2018-08-13 01:26 UTC
