### ISSUE TITLE
Getting duplicate alerts

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/alerts#21] opened 2016-05-09 00:45 UTC
I have 2 alerts which I am getting the same results for multiple times a day. The list of records in each alert email is the same (and it should be different). See images below

This is 2 issues:
- why are the same records appearing in multiple alerts - it should only be notified once?
- ~~why is an ALA citizen science record appearing in the AVH alerts?~~

I'll fork the second issue off.

![image](https://cloud.githubusercontent.com/assets/532845/15101397/82cba078-15d2-11e6-9af1-189000e11c73.png)

![image](https://cloud.githubusercontent.com/assets/532845/15101399/8c9d7dce-15d2-11e6-8e82-44973e6ec052.png)

![image](https://cloud.githubusercontent.com/assets/532845/15101403/98b1be54-15d2-11e6-98f9-cbce5974e1a5.png)

**Comment by adam-collins** [comment] 2024-05-21 23:25
duplicate of newer issues

**Closed by adam-collins** 2024-05-21 23:25 UTC
Labels: bug
